name: ts_definition
version: 1.0.0-alpha+2
description: Parse TypeScript interfaces, and generate (de)serializable Dart classes.
author: Tobe O <thosakwe@gmail.com>
homepage: https://github.com/thosakwe/ts_definition
environment:
  sdk: ">=1.19.0"
dependencies:
  antlr4dart: ^0.7.0
  build: ^0.9.0
  dart_style: ^1.0.0
  indenting_buffer: ^1.0.0
  inflection: ^0.4.1
  recase: ^1.0.0
  symbol_table: ^1.0.0
dev_dependencies:
  build_runner: ^0.3.0
  build_test: ^0.6.0
executables:
  ts_definition: main